#!/bin/bash

set -e

<% if_p('env.http_proxy') do |http_proxy| %>
export HTTP_PROXY="<%= http_proxy %>"
export http_proxy="<%= http_proxy %>"
<% end %>

<% if_p('env.https_proxy') do |https_proxy| %>
export HTTPS_PROXY="<%= https_proxy %>"
export https_proxy="<%= https_proxy %>"
<% end %>

<% if_p('env.no_proxy') do |no_proxy| %>
export NO_PROXY="<%= no_proxy %>"
export no_proxy="<%= no_proxy %>"
<% end %>

BOSH_PACKAGES_DIR=${BOSH_PACKAGES_DIR:-/var/vcap/packages}
BOSH_JOBS_DIR=${BOSH_JOBS_DIR:-/var/vcap/jobs}

export PATH="${BOSH_PACKAGES_DIR}/stackit_cpi/bin:${PATH}"

export LOG_FILE="/tmp/stackit-cpi.log"

if [ -d /var/vcap/sys/log/stackit_cpi ] ; then
  export LOG_FILE="/var/vcap/sys/log/stackit_cpi/stackit-cpi.log"
fi

exec \
  "${BOSH_PACKAGES_DIR}/stackit_cpi/bin/stackit-cpi" \
  -configPath "${BOSH_JOBS_DIR}/stackit_cpi/config/cpi.json"
